print(False or False)
print(False or True)
print("TRUE" or True)

print("Not" + str(True))
print(not False)
print("NOT" + str(False))
print("hello" == "hello")
print("test" == 1)
print(1 == 1 and (not("testing" == 1 or 1 == 0)))